SWEP.PrintName = "HK 416 F"
SWEP.Base = "weapon_mvsa_base"
SWEP.ViewModel = "models/weapons/c_hk416f.mdl"
SWEP.WorldModel = "models/weapons/w_357.mdl"
SWEP.Spawnable = true
SWEP.AdminOnly = false
SWEP.HoldType = "ar2"
SWEP.Primary.ClipSize = 30 -- Size of a clip
SWEP.Primary.DefaultClip = 30 -- Default number of bullets in a clip
SWEP.Primary.Ammo = "ar2"
SWEP.Primary.RPM = 850
SWEP.Primary.Sound = Sound("Weapon_AR15.Single")
SWEP.Primary.Spread = .02 -- Spread while not aiming
SWEP.Primary.IronAccuracy = .005 -- Spread while aiming
SWEP.DryFireSound = Sound("Weapon_Pistol.Empty")
SWEP.FireSelectSound = Sound("Weapon_AR15.fireselect")
SWEP.IronSightsPos = Vector(-2.82, -5, 1.01)
SWEP.IronSightsAng = Vector(0, 0, 0)
SWEP.VerticalKick = 0.5
SWEP.HorizontalKick = 0.125